config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :session
  resources :passwords, param: :token

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Kill stale service workers from other apps that previously ran on this port
  get "pwa-service-worker.js", to: proc { [200, { "Content-Type" => "application/javascript" }, ["self.registration.unregister()"]] }
  get "apple-icon.png", to: proc { [404, {}, [""]] }

  resources :budgets, only: %i[index edit update] do
    collection do
      get ":date", to: "budgets#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
    end

    resources :expenses, only: %i[index create destroy] do
      collection do
        get ":date", to: "expenses#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
      end
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Welcome to HOBO!
    </h1>
    <p class="subtitle">
      Highly Opinionated <strong>Budget</strong> Organizer!
    </p>

    <% if Current.user %>
      <%= link_to "Expenses", budgets_path %><br/>
      <%= link_to "Logout", session_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Login", session_path %>
    <% end %>
  </div>
</section>