config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :session
  resources :passwords, param: :token

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Kill stale service workers from other apps that previously ran on this port
  get "pwa-service-worker.js", to: proc { [200, { "Content-Type" => "application/javascript" }, ["self.registration.unregister()"]] }
  get "apple-icon.png", to: proc { [404, {}, [""]] }

  resources :budgets, only: %i[index edit update] do
    collection do
      get ":date", to: "budgets#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
    end

    resources :expenses, only: %i[index create destroy] do
      collection do
        get ":date", to: "expenses#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
      end
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

class ExpensesController < ApplicationController
  before_action :find_budget

  def index
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.current.beginning_of_month
    @expenses = @budget.expenses.with_creator.for_month(@date).ordered
  end

  def create
    @budget.expenses.create!(amount: expense_amount, date: expense_date)

    render json: {}, status: :created
  end

  def destroy
    expense = @budget.expenses.find(params[:id])
    expense.destroy!

    redirect_to date_budget_expenses_path(@budget, expense.date.beginning_of_month)
  end

  private

  def find_budget
    @budget = Budget.find(params[:budget_id])
  end

  def expense_amount
    amount = expense_params[:digits].to_i
    expense_params[:is_refund] == "true" ? -amount : amount
  end

  def expense_date
    Date.parse(expense_params[:date])
  end

  def expense_params
    params.require(:expense).permit(:budget_id, :digits, :date, :is_refund)
  end
end

app/helpers/expenses_helper.rb
# frozen_string_literal: true

module ExpensesHelper
end

app/views/expenses/_budget.html.erb
<div class="flex bg-gray-100 p-1 rounded-lg shadow-md">
  <div class="flex items-center space-x-2">
    <div class="bg-green-500 rounded-sm text-slate-200 w-8 h-8 flex justify-center items-center">
      <i class="<%= budget.icon %>"></i>
    </div>
    <span class="text text-slate-700"><%= budget.name %></span>
  </div>
  <div class="ml-1">
    <span class="text-lg text-slate-700"><%= number_to_currency(budget.spent || 0.0, precision: 0) %></span>
  </div>
</div>

app/views/expenses/_month_selector.html.erb
<div class="flex flex-row mt-4">
  <%= link_to prev_link, class: "flex-initial p-4" do %>
    <i class="fa-solid fa-arrow-left-long"></i>
  <% end %>

  <h1 class="text-3xl flex-auto text-center my-auto"><%= link_to @date.strftime("%B %Y"), expenses_path(date: @date) %></h1>

  <%= link_to next_link, class: "flex-initial p-4" do %>
    <i class="fa-solid fa-arrow-right-long"></i>
  <% end %>
</div>

app/views/expenses/index.html.erb
<div class="section">
  <div class="container">
    <%= render "budgets/month_selector", prev_link: date_budget_expenses_path(@budget, @date.prev_month), next_link: date_budget_expenses_path(@budget, @date.next_month) %>

    <nav class="level is-mobile">
      <div class="level-left">
        <h2 class="subtitle is-3">
          <%= @budget.name %>
          <%= link_to edit_budget_path(@budget), class: "ml-2" do %>
            <span class="icon is-small has-text-grey"><i class="fas fa-pencil-alt"></i></span>
          <% end %>
        </h2>
      </div>
      <div class="level-right">
        <h2 class="subtitle is-3"><%= number_to_currency(@budget.amount, precision: 0) %></h2>
      </div>
    </nav>

    <% total = 0 %>
    <table class="table is-striped is-fullwidth">
      <thead>
        <tr>
          <th>Day</th>
          <th>Spender</th>
          <th class="has-text-right">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @expenses.each do |expense| %>
          <%
            total += expense.amount
            date = expense.date
          %>
          <tr class="<%= 'has-background-success-light' if expense.amount < 0 %>">
            <td><%= date.day %></td>
            <td><%= expense.creator.first_name %></td>
            <td class="has-text-right <%= 'has-text-success' if expense.amount < 0 %>">
              <%= link_to number_to_currency(expense.amount, precision: 0), budget_expense_path(@budget, expense),
                          data: { turbo_method: :delete,
                                  turbo_confirm: "Delete this expense?" } %>
            </td>
          </tr>
        <% end %>

        <tr>
          <td colspan="3" class="has-text-centered has-text-weight-medium">
            Budget total: <%= number_to_currency(total, precision: 0) %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>