config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :session
  resources :passwords, param: :token

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Kill stale service workers from other apps that previously ran on this port
  get "pwa-service-worker.js", to: proc { [200, { "Content-Type" => "application/javascript" }, ["self.registration.unregister()"]] }
  get "apple-icon.png", to: proc { [404, {}, [""]] }

  resources :budgets, only: %i[index edit update] do
    collection do
      get ":date", to: "budgets#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
    end

    resources :expenses, only: %i[index create destroy] do
      collection do
        get ":date", to: "expenses#index", as: :date, constraints: { date: /\d{4}-\d{2}-\d{2}/ }, format: false
      end
    end
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= content_for(:title) || "HOBO: Highly Opinionated Budget Organizer" %></title>

    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />

    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-status-bar-style" content="black" />
    <meta name="theme-color" content="#b22222" />

    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icon-32.png">

    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/2de86b198d.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
    <%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>

    <%= yield %>
  </body>
</html>